name: rehlko_customer_care
description: A new Flutter project for Rehlko Customer Care.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 3.4.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  file_picker: ^10.3.1
  open_filex: ^4.3.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  syncfusion_flutter_pdfviewer: ^30.2.6
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo_192.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo_192.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/