// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5IcMoSNboX7Gq7KMcfaD45-CCVuIuLeY',
    appId: '1:28980358812:web:a465b3679099fc4def0759',
    messagingSenderId: '28980358812',
    projectId: 'rehlko-dd990',
    authDomain: 'rehlko-dd990.firebaseapp.com',
    storageBucket: 'rehlko-dd990.firebasestorage.app',
    measurementId: 'G-46J3B6NKM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gBDjpiC0Gy9fLyCklUMLR-FoMCOZnek',
    appId: '1:28980358812:android:8afc7e798fc49607ef0759',
    messagingSenderId: '28980358812',
    projectId: 'rehlko-dd990',
    storageBucket: 'rehlko-dd990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULyY53s1rmuOnbJzDog1CN1O4J_U6S8w',
    appId: '1:28980358812:ios:34d45548030b9c45ef0759',
    messagingSenderId: '28980358812',
    projectId: 'rehlko-dd990',
    storageBucket: 'rehlko-dd990.firebasestorage.app',
    iosBundleId: 'com.rehlko.master.maven.rehlkoCustomerCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULyY53s1rmuOnbJzDog1CN1O4J_U6S8w',
    appId: '1:28980358812:ios:ad102096b2a1e9e3ef0759',
    messagingSenderId: '28980358812',
    projectId: 'rehlko-dd990',
    storageBucket: 'rehlko-dd990.firebasestorage.app',
    iosBundleId: 'com.example.rehlkoCustomerCareWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5IcMoSNboX7Gq7KMcfaD45-CCVuIuLeY',
    appId: '1:28980358812:web:e71f3b5b1b72e071ef0759',
    messagingSenderId: '28980358812',
    projectId: 'rehlko-dd990',
    authDomain: 'rehlko-dd990.firebaseapp.com',
    storageBucket: 'rehlko-dd990.firebasestorage.app',
    measurementId: 'G-4J5HR1JSZQ',
  );

}